# Inicio y carga de datos

In [8]:
# "pd" es el alias corto mundialmente utilizado
import pandas as pd

# NumPy nos va a hacer falta en algún momento
import numpy as np
df_insurance = pd.read_csv('https://raw.githubusercontent.com/SonikoKatsura/CURSO_PARO_IA/refs/heads/main/Rober_IA/datos/insurance.csv', sep=',')
df_insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [7]:
df_insurance.columns.to_list()

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']

In [12]:
df_insurance.sample(20)

      age     sex     bmi  children smoker     region      charges
1013   48    male  32.300         1     no  northwest   8765.24900
164    37    male  29.640         0     no  northwest   5028.14660
1052   49    male  29.830         1     no  northeast   9288.02670
373    26    male  32.900         2    yes  southwest  36085.21900
95     28  female  37.620         1     no  southeast   3766.88380
127    52  female  37.400         0     no  southwest   9634.53800
80     31    male  26.885         1     no  northeast   4441.21315
630    53    male  36.100         1     no  southwest  10085.84600
525    18  female  33.880         0     no  southeast  11482.63485
958    43    male  34.960         1    yes  northeast  41034.22140
1284   61    male  36.300         1    yes  southwest  47403.88000
832    28  female  23.845         2     no  northwest   4719.73655
137    22    male  25.175         0     no  northwest   2045.68525
425    45    male  24.310         5     no  southeast   9788.86590
557    34    male  34.210         0     no  southeast   3935.17990
776    40    male  32.300         2     no  northwest   6986.69700
1106   49  female  29.925         0     no  northwest   8988.15875
1123   27  female  32.395         1     no  northeast  18903.49141
460    49  female  36.630         3     no  southeast  10381.47870
208    63  female  31.800         0     no  southwest  13880.94900

a) Seleccionar edad, sexo y región de las 3 primeras filas de la tabla

b) Mostras las filas cuyos cargos(charges) sean mayor a 4000

c)Mostrar las columnas desde edad(age) hasta hijos(children), de aquellas filas cuya región sea (northwest)