## CARGA DE LOS DATOS

In [16]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline


import warnings
warnings.filterwarnings("ignore")

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
ruta = '/content/drive/MyDrive/data_loan.csv'

df_loan = pd.read_csv(ruta, sep = ',')

df_loan.sample(10)

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Annual Income,Years in current job,Home Ownership,Number of Open Accounts,Number of Credit Problems,Bankruptcies
64451,7b22fc62-1d65-40fe-9dbb-4888a601bc56,2e642632-9cf6-4a09-9c05-61813e6d0a7e,Fully Paid,540804.0,1129968.0,4 years,Own Home,10.0,1.0,1.0
79274,4f8399e3-a09d-441d-98c9-72186fc5f873,95ca45da-c6ce-47e9-8867-f616895ba509,Fully Paid,494318.0,NaN,10+ years,Home Mortgage,10.0,0.0,0.0
6722,6be612c1-261d-4106-83b2-88d5a6bd0c39,fb402e8c-50e2-4b7f-9faa-895ff382d550,Fully Paid,99999999.0,2185646.0,1 year,Home Mortgage,19.0,0.0,0.0
46542,46eb57aa-3490-4578-afa1-cf8f6802286e,8affccfd-eeca-4615-b30c-199255a288e3,Charged Off,216282.0,574731.0,10+ years,Home Mortgage,10.0,0.0,0.0
53971,5d0e7507-4d70-4cc3-a238-c8245cb9f0e5,c1d79855-42b4-4447-9e36-8ae58714b98f,Charged Off,201542.0,1779141.0,2 years,Home Mortgage,12.0,0.0,0.0
34133,1a3916a1-fd2b-47aa-9889-f8be3fbfc08a,3f1263ae-1bfc-47d4-87fe-de9b069db842,Fully Paid,352264.0,1596266.0,< 1 year,Own Home,24.0,0.0,0.0
83669,da591187-8403-486a-8f7f-930c57a99a9a,6a0f4910-ed03-4bbd-8382-8e6b860fff5f,Fully Paid,547690.0,NaN,10+ years,Own Home,12.0,0.0,0.0
37950,56fc4671-4855-45de-ac76-fa6a1a4f6661,d59608b7-d569-40b2-8c5e-a7079c6b7dc7,Fully Paid,65516.0,1019768.0,1 year,Home Mortgage,8.0,0.0,0.0
4880,8ac3652c-1dca-4b12-9352-b4d7df03cff6,a4995dfe-47d8-4617-9035-812eafe2d84d,Charged Off,627528.0,1925859.0,7 years,Own Home,12.0,0.0,0.0
42596,8d71f5b8-75c2-4b74-bc1e-b26074679eae,3bc3822b-0a4f-4b10-842d-985eaa83cfa8,Fully Paid,659472.0,2278176.0,10+ years,Home Mortgage,14.0,0.0,0.0

### INFORMACIÓN GENERAL DEL DATASET

In [4]:
df_loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Loan ID                    100000 non-null  object
 1   Customer ID                100000 non-null  object
 2   Loan Status                100000 non-null  object
 3   Current Loan Amount        100000 non-null  float64
 4   Annual Income              80846 non-null   float64
 5   Years in current job       95778 non-null   object
 6   Home Ownership             100000 non-null  object
 7   Number of Open Accounts    100000 non-null  float64
 8   Number of Credit Problems  100000 non-null  float64
 9   Bankruptcies               99796 non-null   float64
dtypes: float64(5), object(5)
memory usage: 7.6+ MB

A falta de comprobar contenido de "Years in current job", todo el resto tiene el tipo correcto asignado. Observamos presencia de nulos en "annual Income","Years in current job" y "Bankruptcies"

#### Hay campos con espacios, los corregimos:

In [5]:
df_loan.columns = df_loan.columns.str.replace(' ', '_')

df_loan.columns

Index(['Loan_ID', 'Customer_ID', 'Loan_Status', 'Current_Loan_Amount',
       'Annual_Income', 'Years_in_current_job', 'Home_Ownership',
       'Number_of_Open_Accounts', 'Number_of_Credit_Problems', 'Bankruptcies'],
      dtype='object')

#### Eliminamos campos ID por no aportar info. POSTERIORMENTE eliminamos duplicados:

In [6]:
df_loan.drop(columns = ['Loan_ID', 'Customer_ID'], inplace = True)

df_loan.drop_duplicates(inplace = True)

df_loan.columns

Index(['Loan_Status', 'Current_Loan_Amount', 'Annual_Income',
       'Years_in_current_job', 'Home_Ownership', 'Number_of_Open_Accounts',
       'Number_of_Credit_Problems', 'Bankruptcies'],
      dtype='object')

In [7]:
df_loan.describe()

,Current_Loan_Amount,Annual_Income,Number_of_Open_Accounts,Number_of_Credit_Problems,Bankruptcies
count,8.975400e+04,7.062200e+04,89754.000000,89754.000000,89564.00000
mean,1.305642e+07,1.375883e+06,11.123482,0.165029,0.11556
std,3.329056e+07,1.104904e+06,4.999313,0.478075,0.34796
min,1.080200e+04,7.662700e+04,0.000000,0.000000,0.00000
25%,1.802680e+05,8.478845e+05,8.000000,0.000000,0.00000
50%,3.138740e+05,1.168908e+06,10.000000,0.000000,0.00000
75%,5.323670e+05,1.648915e+06,14.000000,0.000000,0.00000
max,1.000000e+08,1.655574e+08,76.000000,15.000000,7.00000

Observamos en las distribuciones de "Number of Credit Problems" y	"Bankruptcies" valores anómalos en el extremo superior, mientras que en el resto el valo es cero. Dado que estos valores son posibles, esperamos a las gráficas para tomar una decisión.

In [8]:
df_loan.describe(include = 'object')

       Loan_Status Years_in_current_job Home_Ownership
count        89754                85953          89754
unique           2                   11              4
top     Fully Paid            10+ years  Home Mortgage
freq         67117                27736          43530

Campos ID sin validez. Observamos un nº elevado de niveles o clases (valores únicos: 11) en el campo "Years in current job". Lo analizaremos más adelante.

#### Separar variables numéricas y categóricas

In [9]:
variables_numericas = df_loan.select_dtypes(exclude = 'object').columns.to_list()

variables_categoricas = df_loan.select_dtypes(include = 'object').columns.to_list()

variables_numericas

['Current_Loan_Amount',
 'Annual_Income',
 'Number_of_Open_Accounts',
 'Number_of_Credit_Problems',
 'Bankruptcies']

In [10]:
variables_categoricas

['Loan_Status', 'Years_in_current_job', 'Home_Ownership']

In [11]:
for categorica in variables_categoricas:
  print(categorica)
  print(df_loan[categorica].unique(), end='\n\n')
  print(df_loan[categorica].value_counts(), end='\n\n')

Loan_Status
['Fully Paid' 'Charged Off']

Loan_Status
Fully Paid     67117
Charged Off    22637
Name: count, dtype: int64

Years_in_current_job
['8 years' '10+ years' '3 years' '5 years' '< 1 year' '2 years' '4 years'
 '9 years' '7 years' '1 year' nan '6 years']

Years_in_current_job
10+ years    27736
2 years       8253
< 1 year      7365
3 years       7337
5 years       6136
1 year        5830
4 years       5510
6 years       5132
7 years       4989
8 years       4120
9 years       3545
Name: count, dtype: int64

Home_Ownership
['Home Mortgage' 'Own Home' 'Rent' 'HaveMortgage']

Home_Ownership
Home Mortgage    43530
Rent             37843
Own Home          8198
HaveMortgage       183
Name: count, dtype: int64

In [12]:
df_loan.columns

Index(['Loan_Status', 'Current_Loan_Amount', 'Annual_Income',
       'Years_in_current_job', 'Home_Ownership', 'Number_of_Open_Accounts',
       'Number_of_Credit_Problems', 'Bankruptcies'],
      dtype='object')

Solo comentar el nº elevado de niveles o valores distintos de "Years in current job". Posteriormente hebremos de agrupar (todavía no se ha explicado en clase como,

## AÑADIR CAMPO CALCULADO "Total_Problems" como suma de "Number of credit problems" y "Bankruptcies"

In [13]:
df_loan["Total_Problems"] = df_loan["Number_of_Credit_Problems"] + df_loan["Bankruptcies"]

df_loan.head()

,Loan_Status,Current_Loan_Amount,Annual_Income,Years_in_current_job,Home_Ownership,Number_of_Open_Accounts,Number_of_Credit_Problems,Bankruptcies,Total_Problems
0,Fully Paid,445412.0,1167493.0,8 years,Home Mortgage,6.0,1.0,1.0,2.0
1,Fully Paid,262328.0,NaN,10+ years,Home Mortgage,35.0,0.0,0.0,0.0
2,Fully Paid,99999999.0,2231892.0,8 years,Own Home,18.0,1.0,0.0,1.0
3,Fully Paid,347666.0,806949.0,3 years,Own Home,9.0,0.0,0.0,0.0
4,Fully Paid,176220.0,NaN,5 years,Rent,15.0,0.0,0.0,0.0

## CODIFICAR LA VARIABLE OBJETIVO

In [14]:
df_loan.Loan_Status.unique()

array(['Fully Paid', 'Charged Off'], dtype=object)

Vamos a codificarla como:

- "Charged Off": 0
- "Fully Paid": 1

In [17]:
df_loan.Loan_Status.replace({'Charged Off': 0, 'Fully Paid': 1}, inplace=True)

df_loan.Loan_Status.unique()

array([1, 0])

In [18]:
df_loan.columns

Index(['Loan_Status', 'Current_Loan_Amount', 'Annual_Income',
       'Years_in_current_job', 'Home_Ownership', 'Number_of_Open_Accounts',
       'Number_of_Credit_Problems', 'Bankruptcies', 'Total_Problems'],
      dtype='object')

## NOS HACEMOS ALGUNAS PREGUNTAS.

### **-¿Hay relación entre el Loan Status (target) y Annual Income?**

In [19]:
df_loan.groupby(by=['Loan_Status'])['Annual_Income'].agg(['mean','min', 'max'])

                     mean      min          max
Loan_Status
0            1.267790e+06  76627.0  165557393.0
1            1.410712e+06  81092.0   36475440.0

En los impagados se observan cifras mayores de Ingreso, con lo cual la relación con Status no es tan fuerte (debe probablemente de depender también de otras variables)

### **-¿Hay relación entre el Loan Status (target) y el Current Loan Amount?**

In [20]:
df_loan.groupby(by=['Loan_Status'])['Current_Loan_Amount'].agg(['mean','min', 'max'])

                     mean      min         max
Loan_Status
0            3.249752e+05  21450.0    789250.0
1            1.735045e+07  10802.0  99999999.0

La media para los pagados supera en 2 ordenes de magnitud, sin embargo puede ser debido a la presencia de outliers (999999999---)

### **- ¿El tipo de propiedad influye en si se paga o no un préstamo?**

In [22]:
df_loan.groupby(by=['Home_Ownership', 'Loan_Status'])['Loan_Status'].agg('count')

Home_Ownership  Loan_Status
HaveMortgage    0                 31
                1                152
Home Mortgage   0               9909
                1              33621
Own Home        0               2102
                1               6096
Rent            0              10595
                1              27248
Name: Loan_Status, dtype: int64

En los grupos mayoritarios, la relación parece ser la misma: los impagados son aproximadamente un tercio de los pagados

## POR ÚLTIMO GUARDAR EL DATAFRAME PROCESADO

¡¡¡¡OJO!!!! EN ESTE APARTADO NO EJECUTAR NADA AQUI, ES UNA PLANTILLA PARA COPIAR Y PEGAR Y SUSTITUIR DONDE SE NECESITE

In [ ]:
## CASO UTILIZAR GOOGLE DRIVE (COLAB)
# lo guarda en el Drive dentro de una carpeta creada en MI UNIDAD

ruta_guardar_google_drive = '/content/drive/MyDrive/<carpeta si la he elegido>/<nombre del archivo con su extension>'

In [ ]:
## CASO UTILIZAR DISCO DURO LOCAL (JUPYTER LAB)
# LO GUARDA EN LA MISMA CARPETA QUE ESTA EL NOTEBOOK en mi disco duro local del ordenador

ruta_guardar_local_Jupyter = './<nombre del archivo con su extension>'

In [ ]:
df_loan.to_csv(<una de las dos rutas, la utilizada>, index = False)